# Generated by Django 4.0.4 on 2022-05-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_remove_badge_user'),
        ('authentication', '0004_alter_user_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, to='badges.badge'),
        ),
    ]
