# Generated by Django 4.0.4 on 2022-05-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanup',
            name='after_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='before_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
