# Generated by Django 4.0.4 on 2022-05-03 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0002_alter_cleanup_after_img_alter_cleanup_before_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanup',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
