# Generated by Django 4.0.4 on 2022-05-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0003_alter_cleanup_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanup',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleanup',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cleanup',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cleanup',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleanup',
            name='street',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cleanup',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
