# Generated by Django 4.0.4 on 2022-05-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0004_cleanup_city_cleanup_latitude_cleanup_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanup',
            name='after_img',
            field=models.ImageField(blank=True, null=True, upload_to='after_images/'),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='before_img',
            field=models.ImageField(blank=True, null=True, upload_to='before_images/'),
        ),
    ]
