# Generated by Django 4.0.4 on 2022-05-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0005_alter_cleanup_after_img_alter_cleanup_before_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanup',
            name='street',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
