# Generated by Django 4.0.4 on 2022-05-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0006_alter_cleanup_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanup',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
