# Generated by Django 4.0.4 on 2022-05-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0007_alter_cleanup_city_alter_cleanup_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanup',
            name='after_img',
            field=models.ImageField(blank=True, default='noimageavailable.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='before_img',
            field=models.ImageField(blank=True, default='noimageavailable.png', null=True, upload_to=''),
        ),
    ]
