# Generated by Django 4.0.4 on 2022-05-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0008_alter_cleanup_after_img_alter_cleanup_before_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanup',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
