# Generated by Django 4.0.4 on 2022-05-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0009_cleanup_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanup',
            name='after_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='before_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
