# Generated by Django 4.0.4 on 2022-05-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0010_alter_cleanup_after_img_alter_cleanup_before_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanup',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
