# Generated by Django 4.0.4 on 2022-05-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_remove_badge_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='locked_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='badge',
            name='unlocked_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
