# Generated by Django 4.0.4 on 2022-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_alter_badge_locked_image_alter_badge_unlocked_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='locked_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='badge',
            name='unlocked_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
