# Generated by Django 4.0.4 on 2022-05-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_alter_badge_locked_image_alter_badge_unlocked_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='unlocked_image',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
