# Generated by Django 4.0.4 on 2022-05-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_alter_badge_unlocked_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='locked_image',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
