# Generated by Django 4.0.4 on 2022-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_alter_badge_locked_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='locked_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='badge',
            name='unlocked_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
